CREATE TABLE ACCOUNT (
ID NUMERIC(10) PRIMARY KEY,
BANK NUMERIC(10) NOT NULL,
PERSON NUMERIC(10) NOT NULL,
AGENCY VARCHAR(10) NOT NULL,
ACCOUNT_NUMBER VARCHAR(40) NOT NULL UNIQUE,
DIGIT NUMERIC(1) NOT NULL,
BALANCE NUMERIC(10,2) NOT NULL,
TOKEN BYTEA NOT NULL,
ENABLED BOOLEAN NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
UPDATED_AT TIMESTAMP NOT NULL,
CONSTRAINT ACCOUNT_BANK_FK FOREIGN KEY(BANK) REFERENCES BANK(ID),
CONSTRAINT ACCOUNT_PERSON_FK FOREIGN KEY(PERSON) REFERENCES PERSON(ID)
);