CREATE TABLE USER_PERMISSION (
ID_USER_ACCOUNT NUMERIC(10) NOT NULL,
ID_PERMISSION NUMERIC(10) NOT NULL,
CONSTRAINT USER_PERMISSION_PKEY PRIMARY KEY (ID_USER_ACCOUNT, ID_PERMISSION),
CONSTRAINT USER_PERMISSION_USER_ACCOUNT_FK FOREIGN KEY(ID_USER_ACCOUNT) REFERENCES USER_ACCOUNT(ID),
CONSTRAINT USER_PERMISSION_PERMISSION_FK FOREIGN KEY(ID_PERMISSION) REFERENCES PERMISSION(ID)
);