CREATE TABLE PERSON (
ID NUMERIC(10) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
GENDER VARCHAR(6) NOT NULL,
CPF VARCHAR(11) NOT NULL UNIQUE,
RG VARCHAR(7) NOT NULL UNIQUE,
BIRTH_DATE DATE NOT NULL,
PHONE VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
NEIGHBORHOOD VARCHAR(180) NOT NULL,
NUMBER NUMERIC(6) NOT NULL,
CITY VARCHAR(200) NOT NULL,
STATE VARCHAR(150) NOT NULL,
USER_ACCOUNT NUMERIC(10) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL,
UPDATED_AT TIMESTAMP NOT NULL,
CONSTRAINT PERSON_USER_ACCOUNT_FK FOREIGN KEY(USER_ACCOUNT) REFERENCES USER_ACCOUNT(ID)
);